"""empty message

Revision ID: 0c2100935c24
Revises: 
Create Date: 2022-06-18 16:24:52.604395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2100935c24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dota_hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dota_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('quality', sa.Enum('STANDARD', 'BASE', 'INSCRIBED', 'AUSPICIOUS', 'GENUINE', 'INFUSED', 'EXALTED', 'UNUSUAL', 'ELDER', 'FROZEN', 'HEROIC', name='quality'), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'UNCOMMON', 'MYTHICAL', 'RARE', 'IMMORTAL', 'LEGENDARY', 'ARCANA', name='rarity'), nullable=False),
    sa.Column('item_type', sa.Enum('SKIN', 'GEM', 'COURIER', 'TAUNT', 'ITEMS_SET', 'TREASURE', 'TOOL', 'WARDS', 'COMMENTATORS', 'INTERFACE', name='itemtype'), nullable=False),
    sa.Column('slot', sa.Enum('ABILITY_1', 'ABILITY_2', 'ABILITY_3', 'ABILITY_4', 'ACTION_ITEM', 'ANNOUNCER', 'ARMOR', 'ARMS', 'BACK', 'BELT', 'BODY_HEAD', 'COURIER', 'CURSOR_PACK', 'EMBLEM', 'GLOVES', 'HEAD', 'HEROIC_EFFIGY', 'HUB_SKIN', 'LEGS', 'LOADING_SCREEN', 'MEGA_KILL_ANNOUNCER', 'MISC', 'MOUNT', 'MULTI_KILL_BANNER', 'MUSIC', 'N_FA', 'NECK', 'OFF_HAND', 'Shapeshift', 'SHOULDER', 'SUMMONED_UNIT', 'TAIL', 'TAUNT', 'TERRAIN', 'ULTIMATE', 'VOICE', 'WARD', 'WEAPON', 'WEATHER', 'NONE', name='slot'), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['dota_hero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dota_item_name'), 'dota_item', ['name'], unique=True)
    op.create_table('dota_service_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=10), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['dota_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service', 'item_id', name='_dota_service_item_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dota_service_price')
    op.drop_index(op.f('ix_dota_item_name'), table_name='dota_item')
    op.drop_table('dota_item')
    op.drop_table('dota_hero')
    # ### end Alembic commands ###
