version: '3.3'

services:
#  db:
#    image: postgres:13.3
#    environment:
#      POSTGRES_DB: "db"
#      POSTGRES_USER: "user"
#      POSTGRES_PASSWORD: "pass"
#    ports:
#      - "5433:5432"

  server:
    build: .
    command: bash -c "
      flask db upgrade && 
      gunicorn main:app -b 0.0.0.0:80"
    env_file:
      - .env
    ports:
      - "80:80"
  worker:
    build: .
    restart: always
    command: bash -c "
      flask db upgrade &&
      celery -A background.celery_app.app worker -n base -P solo"
    env_file:
      - .env
  dashboard:
    build: .
    restart: always
    command: bash -c "
      celery -A background.celery_app.app flower --port=5555"
    env_file:
      - .env
    depends_on:
      - worker
    ports:
      - "5555:5555"